### ISSUE TITLE
Disconnected lines on the map

### ISSUE THREAD

**Issue by cosi1** [reconhub/epiflows#1]
I managed to remove those ugly horizontal lines from the map, but there's still a problem with locations connected across the Date Line: after zooming the map out, great circle arcs for these connections look like separate, disconnected curves.

A solution to this might be to calculate the arcs as if they were drawn on a plane surface extending from -180 degrees to 180 degrees, so that they can't cross the Date Line.

What do you think?

**Comment by thibautjombart** [comment]
I am not sure I get it.. reproducible example? ;) I think the great circle distance makes sense in the general case, are you talking about:
1. always use air distances as a replacement
2. use air distances only when the display issue occurs
?

**Comment by cosi1** [comment]
Here's a reproducible example:

```r
library(epiflows)
ef = make_epiflows(Mex_travel_2009[[2]], Mex_travel_2009[[1]])
ef = add_coordinates(ef)
# Rinse and repeat when you get OVER_QUERY_LIMIT,
# thanks to the new default behaviour of add_coordinates()
plot(ef)
```

And a picture worth a thousand words:

![epiflows_map](https://user-images.githubusercontent.com/1132922/31852999-ca161a5c-b681-11e7-8a66-5fff62abe179.png)

:-)

**Comment by thibautjombart** [comment]
Hey there
sorry back from a week of teaching. This example looks good to me actually. I think people will understand what it represents. Presumably these become directly linked if you slide the window to the right?

**Comment by cosi1** [comment]
Unfortunately not :-( The way the locations are connected doesn't change after manipulating the view, but if that's ok for the users, I'm fine with it!

**Comment by thibautjombart** [comment]
I think maybe it is fine for now?

**Comment by cosi1** [comment]
Okay! :-)

**Comment by cosi1** [comment]
To be discussed during the hackathon
