### ISSUE TITLE
potential for revamping S3 class epiflows

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epiflows#14]
#### Pro
- use plotting functions
- use handling functions

#### Cons
- misleading terminology (slots 'linelist' and 'contacts')

Option: use `epicontacts`, and only interact with object components through accessors e.g. `get_flows`,  `get_locations` etc.

**Comment by zkamvar** [comment]
I'm on board with this! There's no reason to re-invent the wheel

**Comment by thibautjombart** [comment]
Good progress today! Left to do:

- for anything user-facing, replace terminology `linelist -> locations` and `contacts -> flows`
- add accessors for optional content (e.g. `get_coords`, `get_pop_size`, `get_duration_stay`)
- handle different types of inputs

**Comment by thibautjombart** [comment]
Comments on current state of the constructor (writing down some previous ones too)

Cool stuff!
### Stuff I've done
- make `flows` the first argument
- default `locations = NULL`, and if NULL just create a data.frame with a `$id` generated from the from/to in `flows`

### Stuff to do
- rename the new constructor to `make_epiflows`
- comment out / remove old version

Incidentally this now works:
`vis_epiflows(epiflows(random_flows(20)))`

**Comment by zkamvar** [comment]
closed in #19
