### ISSUE TITLE
New graphics 

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/epiflows#15]
`plot.epiflows` will have a `type` argument calling different functions:

- `vis_epiflows`: the visNetwork versions of the graph; could be directly called from `epicontacts` if we inherit from this class

- `map_epiflows`: Pawel's current maps, only working when spatial coords are present

- `count_epiflows`: or a better name; similar to the ancestry plots from `outbreaker2` (to be done by Thibaut)

**Comment by zkamvar** [comment]
`grid_epiflows` instead of `count_epiflows`?

**Comment by thibautjombart** [comment]
yes

**Comment by zkamvar** [comment]
This was closed in #19
