### ISSUE TITLE
Provide data with coordinates instead of using the add_coordinates function

### ISSUE THREAD

**Issue by Paula-Moraga** [reconhub/epiflows#2]
add_coordinates is a wrapper of the geocode function of the ggmap package. geocode sometimes returns NAs for some locations or can reach the limit retrieval. Do you think it is better we say users need to provide data that include the coordinates of the locations? Then in the documentation we can say that if they do not know the coordinates they can obtain them for example with the geocode function. By doing that users will be able to provide coordinates from other sources, or if they use geocode they can check if geocode is retrieving all the coordinates correctly.

**Comment by cosi1** [comment]
That's why I modified the function a bit :-) Now, with the default settings, you can re-run `add_coordinates()` to obtain *only* the missing locations - even if `geocode()` fails several times, you can simply run the function until no NAs are present (or even do it automatically in a loop).

**Comment by Paula-Moraga** [comment]
That's great! But now I am thinking that sometimes users will use locations pertaining to small areas that `geocode()` cannot find and in these situations they will need to provide the coordinates. Also sometimes `geocode()` provides incorrect coordinates (for example when there are several locations with the same name). 

Can we give an option that enables users to provide the coordinates directly? If they do not have them they can use `add_coordinates()` that is an improvement of `geocode()`. We can also give the option to check and modify by hand the coordinates retrieved by `add_coordinates()`.

**Comment by cosi1** [comment]
Yes, sure! You don't need to run `add_coordinates()` at all to perform calculations and render the map - you can add latitude/longitude columns to your epiflows object manually if you wish.

**Comment by Paula-Moraga** [comment]
Great!
