### ISSUE TITLE
Change name of `epiflows$linelist`

### ISSUE THREAD

**Issue by Paula-Moraga** [reconhub/epiflows#3]
The `epiflows` object has two elements: `linelist` (data.frame with the code, name, population and optionally coordinates) and `flows` (matrix with population flows).
Suggestion 1: Can we change `linelist` by other name (for example `data` so the name gives an idea of what is inside?)
Suggestion 2: First argument of `fn_number_cases_spread()` is `x` which is an `epiflows` object. Can we change the name `x` by `ef`?
By doing that an `epiflows` object called `ef` will be a list containing `data` and `flows`.
I think these changes will help users understand better what is the structure of the `epiflows` objects.

**Comment by cosi1** [comment]
Ad 1) Don't tell that @thibautjombart :rofl: 
But seriously, how about `locations`?

Ad 2) You're welcome :-) Done.

PS. If you change your mind, just revert the last commit ;-)

**Comment by Paula-Moraga** [comment]
1) `locationsinfo`? `locationsdata`?
2) That was quick!
