### ISSUE TITLE
plot.epiflows() when coordinates are missing

### ISSUE THREAD

**Issue by Paula-Moraga** [reconhub/epiflows#4]
I get an error when I do `plot(flows, "MEX")`:
Error in if (antipodal(p1, p2)) { : missing value where TRUE/FALSE needed
I think this is because there are missing coordinates. We need to modify the function to first check all coordinates are non-missing and are in a correct format. If there are NAs return error message. This is the code I run:
(input_data <- Mex_travel_2009
flows <- make_epiflows(input_data[[2]], input_data[[1]])
flows <- add_coordinates(flows)
plot(flows, "MEX")

**Comment by cosi1** [comment]
When you run `plot()` with lat/lon columns present in ef$locationsdata, it assumes that you have already filled coordinate data, and doesn't add this data automatically, but you're right that the error message is too cryptic.

Fixed.

Btw. please notice that after the refactoring the order of parameters to `make_epiflows()` has changed. Now it's easier to make an epiflows object from the example data with:

`ef = do.call(make_epiflows, Mex_travel_2009)`

or

`ef = make_epiflows(Mex_travel_2009[[1]], Mex_travel_2009[[2]])`

**Comment by Paula-Moraga** [comment]
Sometimes after executing `add_coordinates()` again locations are not geocoded because status OVER_QUERY_LIMIT or name locations cannot be found (my example below). We will need to think an error message that describes that this can happen and tell the user he needs to find the coordinates resorting to other methods.  Executing `add_coordinates()` again is not always the solution. But we can think about that later. 

I still get NAs after executing `add_coordinates()` because this:
Warning messages:
1: geocode failed with status OVER_QUERY_LIMIT, location = "Chile" 
2: geocode failed with status OVER_QUERY_LIMIT, location = "Dominican Republic" 
3: geocode failed with status OVER_QUERY_LIMIT, location = "France" 
4: geocode failed with status OVER_QUERY_LIMIT, location = "Guatemala" 
5: geocode failed with status OVER_QUERY_LIMIT, location = "Hong Kong" 
6: geocode failed with status OVER_QUERY_LIMIT, location = "Honduras" 
7: geocode failed with status OVER_QUERY_LIMIT, location = "Luxembourg" 
8: geocode failed with status OVER_QUERY_LIMIT, location = "Netherlands" 
9: geocode failed with status OVER_QUERY_LIMIT, location = "United States of America"

**Comment by cosi1** [comment]
`add_coordinates()` can be run iteratively until all locations are filled - usually it takes 3 to 4 runs for our test set - but I'm open to suggestions on how we could communicate this to the user.

**Comment by Paula-Moraga** [comment]
OK, we will think about that.  Also, I think we should include the coordinates in the example data `Mex_travel_2009`. By doing that the example will always work regardless `add_coordinates()` gives all coordinates or not.

**Comment by thibautjombart** [comment]
Moving this to https://github.com/reconhub/epiflows/issues/15
