### ISSUE TITLE
I can't see the dynamic network

### ISSUE THREAD

**Issue by little2b** [reconhub/epiflows#43]
as your article,i used this code,but i can't see the dynamic network.
`> plot(Brazil_epiflows, type = "network")`

**Comment by thibautjombart** [comment]
Thanks for the report. 
I think this is related to a bug in epicontacts introduced by changes in visNetwork:
https://github.com/reconhub/epicontacts/issues/122

This has been fixed on the github version, which you can install using:
devtools::install_github("reconhub/epicontacts")

Could you try and confirm if it fixes your issue? You'll probably need to restart R after updating epicontacts and restart a new session.

**Comment by little2b** [comment]
Thanks for your answer 
But i used epiflows not epicontacts.If i use the github version epicontacts can fix this issue?

**Comment by thibautjombart** [comment]
Yes but the visualisation under the hood is epicontacts's. Can you try updating and see if it fixes the issue?

**Comment by little2b** [comment]
Thanks very much. I will have try.

**Comment by little2b** [comment]
Thanks  very much. I will have a try.

**Comment by little2b** [comment]
After updating, it fixes the issue. Thank you very much!

**Comment by thibautjombart** [comment]
Great to hear! :)
