### ISSUE TITLE
Shiny and epiflows?

### ISSUE THREAD

**Issue by sherryhuang4** [reconhub/epiflows#44]
Hi, I wanted to plot a dynamic `epiflows` network in a Shiny app; is there support for that yet? If so, what is the syntax? Thank you!

**Comment by cosi1** [comment]
Hello Sherry,

the network returned by `vis_epiflows()` is basically a `visNetwork` object; please see the documentation for how to render these objects in a Shiny app:
http://datastorm-open.github.io/visNetwork/shiny.html

Please let me know if that helps!

**Comment by sherryhuang4** [comment]
This was extremely helpful; thanks so much!
