### ISSUE TITLE
Lealflet options to be set by user

### ISSUE THREAD

**Issue by cosi1** [reconhub/epiflows#5]
As a user I'd like to be able to change the default settings of Leaflet to my own.

TO DO:
* determine which arguments the user would be able to change
* add arguments to the plotting function

**Comment by zkamvar** [comment]
IMO, much of the heavy lifting of `map_epiflows()/plot()` was the steps of translating the flows to a SpatialLinesDataFrame object. This is now available to the user with the function `as.SpatialLinesDataFrame()`. From there, the user just needs to use:

```r
as.SpatialLinesDataFrame(ef) %>% 
  leaflet::leaflet() %>%
  leaflet::addTiles(...) %>%
  leaflet::addPolylines(...) %>%
  leaflet::addLegend(...)
```
